#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>

unsigned int generateRandNum()
{
    int randfd = open("/dev/random", O_RDONLY);
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
        return 0;
    }
    unsigned int randNum;
    read(randfd, &randNum, sizeof(int));
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }
    close(randfd);
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }
    return randNum;
}

int main()
{

    //Populates an array with 10 random numbers generated by your random function (print out each value)
    printf("Generating random numbers: \n");
    unsigned int randarr[10];
    int i;
    for (i = 0; i < 10; i++)
    {
        randarr[i] = generateRandNum();
        printf("\trandom %d: %u\n", i, randarr[i]);
    }

    //Writes the array to a file (w/o using a loop)
    int fin = open("randfile.in", O_WRONLY | O_CREAT, 0666);
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }
    printf("\nWriting numbers to file...\n\n");
    write(fin, randarr, 10 * sizeof(int));
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }

    close(fin);
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }

    unsigned int randarr1[10];
    //Reads that file into a different array (w/o using a loop)
    int readf = open("randfile.in", O_RDONLY);
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }
    printf("Reading numbers from file...\n\n");
    read(readf, &randarr1, 10 * sizeof(int));
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }

    close(readf);
    if (errno) {
        printf("error #: %d error: %s\n", errno, strerror(errno));
    }

    //Prints out the contents of the second array to verify the random numbers are the same from step 1
    printf("Verification that written values were the same:\n");
    for (i = 0; i < 10; i++)
    {
        printf("\trandom %d: %u\n", i, randarr1[i]);
    }

    return 0;
}